name: test-environment
channels:
- mosdef
- omnia
- glotzer
- defaults
dependencies:
- numpy
- mdtraj
- hoomd
# Testing Deps
- pytest >=3.0
- jupyter
- nbformat
- ipykernel
- ipyext
- python-coveralls
- pytest-cov
